apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: {{ .Values.server | quote }}
    email: {{ required "A valid .Values.email entry required!" .Values.email | quote }}
    privateKeySecretRef:
      name: {{ .Release.Name | quote }}
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx